// Figma color variables. Components read hex from here where a prop needs a color (icons, spinners).
module.exports = {
  background: "#ffffff",
  surface: "#ffffff",
  "surface-muted": "#f1f4f8",
  foreground: "#0e1a2b",
  "text-secondary": "#46556a",
  "text-muted": "#5f6e83",
  "text-disabled": "#8494a6",
  border: "#dce3eb",
  "border-subtle": "#e8edf3",
  "border-strong": "#8494a6",
  accent: "#1565c0",
  "accent-strong": "#0d47a1",
  "accent-subtle": "#e3f2fd",
  "accent-foreground": "#ffffff",
  success: "#43a047",
  "success-text": "#2e7d32",
  "success-subtle": "#e8f5e9",
  warning: "#ffc107",
  "warning-text": "#8a5300",
  "warning-subtle": "#fff8e1",
  "on-warning": "#0e1a2b",
  danger: "#e53935",
  "danger-text": "#c62828",
  "danger-subtle": "#ffebee",
  live: "#42a5f5",
  "control-on": "#1565c0",
  "control-track": "#8494a6",
  "control-thumb": "#ffffff",
  "map-land": "#edf0f4",
  "map-road": "#ffffff",
  "map-road-casing": "#d5dce5",
  "map-park": "#d9ecda",
  "map-building": "#e0e5ec",
  "map-water": "#cae6fc",
  "map-label": "#5f6e83",
};
