-- ParaTrack schema: tables, RLS, driver functions and the stale-vehicle job.
-- Clients reach tables only through the grants below (new tables are not exposed by default).
-- Driver writes go through security definer functions, which check auth.uid() themselves.

create extension if not exists postgis with schema extensions;
create extension if not exists pg_cron with schema pg_catalog;
grant usage on schema cron to postgres;
grant all privileges on all tables in schema cron to postgres;

create type public.vehicle_type as enum ('jeep', 'ejeep', 'bus', 'shuttle');
create type public.fare_type as enum ('regular', 'student', 'senior', 'pwd');
create type public.trip_status as enum ('tracking', 'onboard', 'ended');
create type public.notification_kind as enum ('arrival', 'service');

-- Tables

create table public.profiles (
  id uuid primary key references auth.users on delete cascade,
  display_name text,
  fare_type public.fare_type not null default 'regular',
  arrival_alerts boolean not null default true,
  service_updates boolean not null default true,
  alert_minutes smallint not null default 2 check (alert_minutes between 1 and 15),
  created_at timestamptz not null default now()
);

create table public.operators (
  id uuid primary key default gen_random_uuid(),
  name text,
  code text unique not null
);

create table public.routes (
  id uuid primary key default gen_random_uuid(),
  name text unique,
  vehicle_type public.vehicle_type,
  color text,
  geom extensions.geometry(LineString, 4326) not null,
  length_m double precision not null,
  headway_min smallint,
  base_fare numeric(6, 2),
  base_km numeric(5, 2),
  per_km numeric(5, 2),
  active boolean not null default true
);

create table public.stops (
  id uuid primary key default gen_random_uuid(),
  name text,
  geom extensions.geometry(Point, 4326)
);
create index stops_geom_idx on public.stops using gist (geom);

create table public.route_stops (
  route_id uuid references public.routes on delete cascade,
  stop_id uuid not null references public.stops on delete cascade,
  seq smallint,
  offset_m double precision not null check (offset_m >= 0),
  primary key (route_id, seq),
  unique (route_id, stop_id)
);
create index route_stops_stop_id_idx on public.route_stops (stop_id);

create table public.vehicles (
  id uuid primary key default gen_random_uuid(),
  operator_id uuid not null references public.operators,
  route_id uuid not null references public.routes,
  label text,
  plate text unique,
  capacity smallint not null check (capacity > 0)
);
create index vehicles_operator_id_idx on public.vehicles (operator_id);
create index vehicles_route_id_idx on public.vehicles (route_id);

create table public.drivers (
  user_id uuid primary key references auth.users on delete cascade,
  operator_id uuid not null references public.operators on delete cascade,
  vehicle_id uuid unique references public.vehicles on delete cascade,
  verified_at timestamptz not null default now()
);
create index drivers_operator_id_idx on public.drivers (operator_id);

create table public.driver_verify_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users on delete cascade,
  created_at timestamptz not null default now()
);
create index driver_verify_attempts_user_id_idx on public.driver_verify_attempts (user_id, created_at);

create table public.vehicle_live (
  vehicle_id uuid primary key references public.vehicles on delete cascade,
  driver_id uuid references auth.users on delete set null,
  online boolean not null default false,
  lat double precision,
  lng double precision,
  heading real,
  accuracy real,
  progress_m double precision not null default 0,
  speed_mps real not null default 0,
  seats_taken smallint not null default 0 check (seats_taken >= 0),
  marked_full boolean not null default false,
  updated_at timestamptz not null default now()
);
create index vehicle_live_driver_id_idx on public.vehicle_live (driver_id);

create table public.trips (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users on delete cascade,
  vehicle_id uuid references public.vehicles on delete cascade,
  board_stop_id uuid references public.stops on delete cascade,
  alight_stop_id uuid references public.stops on delete cascade,
  status public.trip_status not null default 'tracking',
  arrival_alert boolean not null default true,
  para_alert boolean not null default true,
  arrival_sent_at timestamptz,
  para_sent_at timestamptz,
  full_sent_at timestamptz,
  created_at timestamptz not null default now()
);
create index trips_user_id_idx on public.trips (user_id);
create index trips_vehicle_id_idx on public.trips (vehicle_id);
create index trips_board_stop_id_idx on public.trips (board_stop_id);
create index trips_alight_stop_id_idx on public.trips (alight_stop_id);

create table public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users on delete cascade,
  kind public.notification_kind,
  title text,
  body text,
  data jsonb not null default '{}',
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create index notifications_user_id_created_at_idx on public.notifications (user_id, created_at desc);

create table public.announcements (
  id bigint generated by default as identity primary key,
  route_id uuid references public.routes on delete cascade,
  title text,
  body text,
  created_at timestamptz not null default now()
);
create index announcements_route_id_idx on public.announcements (route_id);

create table public.saved_places (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users on delete cascade,
  label text,
  stop_id uuid references public.stops on delete cascade
);
create index saved_places_user_id_idx on public.saved_places (user_id);
create index saved_places_stop_id_idx on public.saved_places (stop_id);

create table public.saved_routes (
  user_id uuid not null default auth.uid() references auth.users on delete cascade,
  route_id uuid not null references public.routes on delete cascade,
  primary key (user_id, route_id)
);
create index saved_routes_route_id_idx on public.saved_routes (route_id);

create table public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users on delete cascade,
  kind text not null check (kind in ('web', 'expo')),
  token text not null,
  keys jsonb,
  created_at timestamptz not null default now(),
  unique (user_id, token)
);

-- Triggers

create function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id) values (new.id);
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Users who signed up before this migration.
insert into public.profiles (id) select id from auth.users on conflict do nothing;

create function public.set_route_length()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.length_m := extensions.st_length(new.geom::extensions.geography);
  return new;
end;
$$;

create trigger routes_set_length
  before insert or update on public.routes
  for each row execute function public.set_route_length();

create function public.check_trip_stops()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if exists (
    select 1
    from unnest(array[new.board_stop_id, new.alight_stop_id]) as s(stop_id)
    where s.stop_id is not null
      and not exists (
        select 1
        from public.route_stops rs
        join public.vehicles v on v.route_id = rs.route_id
        where v.id = new.vehicle_id and rs.stop_id = s.stop_id
      )
  ) then
    raise exception 'stop_not_on_route';
  end if;
  return new;
end;
$$;

create trigger trips_check_stops
  before insert or update of vehicle_id, board_stop_id, alight_stop_id on public.trips
  for each row execute function public.check_trip_stops();

revoke execute on function public.handle_new_user(), public.set_route_length(), public.check_trip_stops()
  from public, anon, authenticated;

-- Grants and RLS (matrix in docs/superpowers/plans/2026-10-04-phase-2-3-core-and-database.md)

revoke all on
  public.profiles, public.operators, public.routes, public.stops, public.route_stops,
  public.vehicles, public.drivers, public.driver_verify_attempts, public.vehicle_live,
  public.trips, public.notifications, public.announcements, public.saved_places,
  public.saved_routes, public.push_subscriptions
from anon, authenticated;

grant all on
  public.profiles, public.operators, public.routes, public.stops, public.route_stops,
  public.vehicles, public.drivers, public.driver_verify_attempts, public.vehicle_live,
  public.trips, public.notifications, public.announcements, public.saved_places,
  public.saved_routes, public.push_subscriptions
to service_role;
grant usage, select on all sequences in schema public to service_role;

alter table public.profiles enable row level security;
alter table public.operators enable row level security;
alter table public.routes enable row level security;
alter table public.stops enable row level security;
alter table public.route_stops enable row level security;
alter table public.vehicles enable row level security;
alter table public.drivers enable row level security;
alter table public.driver_verify_attempts enable row level security;
alter table public.vehicle_live enable row level security;
alter table public.trips enable row level security;
alter table public.notifications enable row level security;
alter table public.announcements enable row level security;
alter table public.saved_places enable row level security;
alter table public.saved_routes enable row level security;
alter table public.push_subscriptions enable row level security;

-- Public reads. vehicles hides operator_id through column grants.
grant select on public.routes, public.stops, public.route_stops, public.announcements, public.vehicle_live
  to anon, authenticated;
grant select (id, route_id, label, plate, capacity) on public.vehicles to anon, authenticated;

create policy "Anyone reads routes" on public.routes for select to anon, authenticated using (true);
create policy "Anyone reads stops" on public.stops for select to anon, authenticated using (true);
create policy "Anyone reads route stops" on public.route_stops for select to anon, authenticated using (true);
create policy "Anyone reads announcements" on public.announcements for select to anon, authenticated using (true);
create policy "Anyone reads vehicles" on public.vehicles for select to anon, authenticated using (true);
create policy "Anyone reads online vehicles" on public.vehicle_live for select to anon, authenticated using (online);

-- Profiles: read and update own
grant select on public.profiles to authenticated;
grant update (display_name, fare_type, arrival_alerts, service_updates, alert_minutes) on public.profiles
  to authenticated;

create policy "Users read own profile" on public.profiles for select to authenticated
  using ((select auth.uid()) = id);
create policy "Users update own profile" on public.profiles for update to authenticated
  using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

-- Owner CRUD
grant select, insert, update, delete on public.trips, public.saved_places, public.saved_routes, public.push_subscriptions
  to authenticated;

create policy "Users manage own trips" on public.trips for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Users manage own saved places" on public.saved_places for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Users manage own saved routes" on public.saved_routes for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Users manage own push subscriptions" on public.push_subscriptions for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

-- Notifications: read own, set read_at only
grant select on public.notifications to authenticated;
grant update (read_at) on public.notifications to authenticated;

create policy "Users read own notifications" on public.notifications for select to authenticated
  using ((select auth.uid()) = user_id);
create policy "Users mark own notifications read" on public.notifications for update to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

-- Drivers: read own. operators and driver_verify_attempts get no client grants or policies.
grant select on public.drivers to authenticated;

create policy "Drivers read own row" on public.drivers for select to authenticated
  using ((select auth.uid()) = user_id);

alter publication supabase_realtime add table public.vehicle_live, public.notifications;

-- Driver functions. Errors are plain codes the apps map to copy.

create function public.verify_driver(p_operator_code text, p_plate text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_vehicle record;
begin
  if v_uid is null or auth.jwt() ->> 'is_anonymous' = 'true' then
    raise exception 'phone_required';
  end if;

  if (
    select count(*) from public.driver_verify_attempts a
    where a.user_id = v_uid and a.created_at > now() - interval '1 hour'
  ) >= 5 then
    raise exception 'too_many_attempts';
  end if;

  select v.id, v.operator_id, v.label, v.plate, v.capacity, v.route_id, r.name as route_name
  into v_vehicle
  from public.vehicles v
  join public.operators o on o.id = v.operator_id
  join public.routes r on r.id = v.route_id
  where o.code = p_operator_code
    and upper(regexp_replace(v.plate, '[\s-]', '', 'g')) = upper(regexp_replace(p_plate, '[\s-]', '', 'g'));

  if not found then
    insert into public.driver_verify_attempts (user_id) values (v_uid);
    -- A raise would roll the attempt back, so answer with PostgREST's error status and body instead.
    -- supabase-js reports it like a raised error: error.message = 'invalid_code_or_plate'.
    perform set_config('response.status', '400', true);
    return jsonb_build_object('code', 'P0001', 'message', 'invalid_code_or_plate', 'details', null, 'hint', null);
  end if;

  -- One driver per vehicle: verifying moves the vehicle to the caller.
  delete from public.drivers d where d.vehicle_id = v_vehicle.id and d.user_id <> v_uid;
  insert into public.drivers (user_id, operator_id, vehicle_id, verified_at)
  values (v_uid, v_vehicle.operator_id, v_vehicle.id, now())
  on conflict (user_id) do update
    set operator_id = excluded.operator_id, vehicle_id = excluded.vehicle_id, verified_at = excluded.verified_at;

  return jsonb_build_object(
    'vehicle_id', v_vehicle.id,
    'label', v_vehicle.label,
    'plate', v_vehicle.plate,
    'capacity', v_vehicle.capacity,
    'route_id', v_vehicle.route_id,
    'route_name', v_vehicle.route_name
  );
end;
$$;

create function public.start_shift()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_vehicle uuid;
  v_live public.vehicle_live;
begin
  select d.vehicle_id into v_vehicle from public.drivers d where d.user_id = v_uid;
  if v_vehicle is null then
    raise exception 'not_a_driver';
  end if;

  if exists (
    select 1 from public.vehicle_live l
    where l.vehicle_id = v_vehicle
      and l.online
      and l.driver_id is distinct from v_uid
      and l.updated_at > now() - interval '5 minutes'
  ) then
    raise exception 'vehicle_in_use';
  end if;

  -- A driver is online in one vehicle at a time.
  update public.vehicle_live set online = false
  where driver_id = v_uid and vehicle_id <> v_vehicle and online;

  insert into public.vehicle_live (vehicle_id, driver_id, online, seats_taken, marked_full, updated_at)
  values (v_vehicle, v_uid, true, 0, false, now())
  on conflict (vehicle_id) do update
    set driver_id = excluded.driver_id, online = true, seats_taken = 0, marked_full = false, updated_at = now()
  returning * into v_live;

  return to_jsonb(v_live);
end;
$$;

create function public.driver_ping(
  p_lat double precision,
  p_lng double precision,
  p_speed real default null,
  p_heading real default null,
  p_accuracy real default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_live public.vehicle_live;
  v_route_id uuid;
  v_len double precision;       -- route length in meters
  v_line extensions.geometry;   -- route in UTM meters
  v_scale double precision;     -- route meters per UTM meter
  v_pt extensions.geometry;
  v_from double precision;
  v_to double precision;
  v_window extensions.geometry;
  v_try integer;
  v_along double precision;
  v_progress double precision;
  v_moved double precision := 0;
  v_speed double precision;
begin
  select l.* into v_live from public.vehicle_live l
  where l.driver_id = auth.uid() and l.online
  for update;
  if not found then
    raise exception 'not_online';
  end if;

  if p_lat is null or p_lng is null or p_lat not between -90 and 90 or p_lng not between -180 and 180 then
    raise exception 'invalid_point';
  end if;

  -- ponytail: UTM 51N (EPSG:32651) covers Tarlac, pick the zone per route if the app leaves zone 51
  select r.id, r.length_m, extensions.st_transform(r.geom, 32651)
  into v_route_id, v_len, v_line
  from public.vehicles v
  join public.routes r on r.id = v.route_id
  where v.id = v_live.vehicle_id;
  v_scale := v_len / extensions.st_length(v_line);
  v_pt := extensions.st_transform(extensions.st_setsrid(extensions.st_makepoint(p_lng, p_lat), 4326), 32651);

  -- Loops often run out and back on one street, so search ahead of the current progress first.
  -- The window starts 50 m back to absorb GPS jitter and wraps past the end of the loop.
  -- ponytail: 2 km forward window, tune if loops cross themselves
  v_from := (v_live.progress_m - 50) / v_len;
  v_from := v_from - floor(v_from);
  v_to := v_from + least(2050 / v_len, 1);
  if v_to <= 1 then
    v_window := extensions.st_linesubstring(v_line, v_from, v_to);
  else
    v_window := extensions.st_makeline(
      extensions.st_linesubstring(v_line, v_from, 1),
      extensions.st_linesubstring(v_line, 0, v_to - 1)
    );
  end if;

  -- Try the window, then the whole line. Within one, take the earliest segment within 10 m of the
  -- closest, since overlapping out and back legs tie on distance.
  select c.try, f.along_m * v_scale
  into v_try, v_along
  from (values (1, v_window), (2, v_line)) as c(try, line)
  cross join lateral (
    select s.start_m + extensions.st_linelocatepoint(s.geom, v_pt) * s.len as along_m
    from (
      select
        d.path[1] as i,
        d.geom,
        extensions.st_length(d.geom) as len,
        extensions.st_distance(d.geom, v_pt) as dist,
        min(extensions.st_distance(d.geom, v_pt)) over () as min_dist,
        coalesce(sum(extensions.st_length(d.geom)) over (
          order by d.path[1] rows between unbounded preceding and 1 preceding
        ), 0) as start_m
      from extensions.st_dumpsegments(c.line) d
    ) s
    where s.len > 0 and s.dist <= 200 and s.dist <= s.min_dist + 10
    order by s.i
    limit 1
  ) f
  order by c.try
  limit 1;

  if v_try = 1 then
    -- Progress never moves back within the window.
    v_moved := greatest(v_along - 50, 0);
    v_progress := v_live.progress_m + v_moved;
  elsif v_try = 2 then
    v_progress := v_along;
    v_moved := v_progress - v_live.progress_m;
    v_moved := v_moved - v_len * floor(v_moved / v_len);
  else
    v_progress := v_live.progress_m;
  end if;
  v_progress := v_progress - v_len * floor(v_progress / v_len);

  v_speed := 0.7 * v_live.speed_mps + 0.3 * coalesce(
    case when p_speed >= 0 then p_speed end,
    v_moved / greatest(extract(epoch from now() - v_live.updated_at)::double precision, 1)
  );
  v_speed := least(greatest(v_speed, 0), 40);

  update public.vehicle_live set
    lat = p_lat,
    lng = p_lng,
    heading = p_heading,
    accuracy = p_accuracy,
    progress_m = v_progress,
    speed_mps = v_speed,
    updated_at = now()
  where vehicle_id = v_live.vehicle_id;

  return jsonb_build_object(
    'vehicle_id', v_live.vehicle_id,
    'route_id', v_route_id,
    'route_length_m', v_len,
    'progress_m', v_progress,
    'speed_mps', v_speed::real,
    'on_route', v_try is not null
  );
end;
$$;

create function public.driver_set_seats(p_count integer default null, p_full boolean default null)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_live public.vehicle_live;
  v_capacity smallint;
  v_was_full boolean;
begin
  select l.* into v_live from public.vehicle_live l
  where l.driver_id = auth.uid() and l.online
  for update;
  if not found then
    raise exception 'not_online';
  end if;

  select v.capacity into v_capacity from public.vehicles v where v.id = v_live.vehicle_id;
  v_was_full := v_live.marked_full or v_live.seats_taken >= v_capacity;

  update public.vehicle_live set
    seats_taken = case when p_count is null then seats_taken else least(greatest(p_count, 0), v_capacity) end,
    marked_full = coalesce(p_full, marked_full)
  where vehicle_id = v_live.vehicle_id
  returning * into v_live;

  return jsonb_build_object(
    'seats_taken', v_live.seats_taken,
    'capacity', v_capacity,
    'marked_full', v_live.marked_full,
    'was_full', v_was_full,
    'is_full', v_live.marked_full or v_live.seats_taken >= v_capacity
  );
end;
$$;

create function public.tracking_count(p_vehicle_id uuid)
returns integer
language sql
stable
security definer
set search_path = ''
as $$
  select count(*)::integer from public.trips t
  where t.vehicle_id = p_vehicle_id and t.status in ('tracking', 'onboard');
$$;

create function public.end_shift()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_vehicle uuid;
begin
  update public.vehicle_live set online = false
  where driver_id = auth.uid() and online
  returning vehicle_id into v_vehicle;
  if v_vehicle is null then
    raise exception 'not_online';
  end if;

  return jsonb_build_object('vehicle_id', v_vehicle, 'trackers', public.tracking_count(v_vehicle));
end;
$$;

revoke execute on function
  public.verify_driver(text, text),
  public.start_shift(),
  public.driver_ping(double precision, double precision, real, real, real),
  public.driver_set_seats(integer, boolean),
  public.end_shift(),
  public.tracking_count(uuid)
from public, anon;

grant execute on function
  public.verify_driver(text, text),
  public.start_shift(),
  public.driver_ping(double precision, double precision, real, real, real),
  public.driver_set_seats(integer, boolean),
  public.end_shift(),
  public.tracking_count(uuid)
to authenticated, service_role;

-- Vehicles silent for 5 minutes go offline.
select cron.schedule(
  'stale-vehicles',
  '* * * * *',
  $$update public.vehicle_live set online = false where online and updated_at < now() - interval '5 minutes'$$
);

-- Admin only: runs a cron job's SQL now, so tests need not wait for the schedule.
create function public.run_cron_job(p_name text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_command text;
begin
  select j.command into v_command from cron.job j where j.jobname = p_name;
  if v_command is null then
    raise exception 'no_such_job';
  end if;
  execute v_command;
end;
$$;

revoke execute on function public.run_cron_job(text) from public, anon, authenticated;
grant execute on function public.run_cron_job(text) to service_role;
